"""Pull the abstract and the protocol paragraphs verbatim out of the manuscript .docx files.

Run this to (re)generate ``protocols_verbatim.py``.  ``build_geo_metadata.py
--verify-protocols`` re-runs the same extraction and diffs it against the committed constants.
"""

import html
import re
import sys
import zipfile
from pathlib import Path

STAR_METHODS = Path(
    "/Users/henrysanford/Dropbox @RU Dropbox/Vinogradova Laboratory/Macrophage project/"
    "Manuscript 1/06_Nat Immunol/03_Supplementary data/"
    "04_STARMethods_KeyResourcesTable_20260724.docx"
)

MAIN_TEXT = Path(
    "/Users/henrysanford/Dropbox @RU Dropbox/Vinogradova Laboratory/Macrophage project/"
    "Manuscript 1/06_Nat Immunol/04_Main text/"
    "Macrophage_text_20260730_v9.docx"
)
ABSTRACT_HEADING = "Abstract:"
MIN_ABSTRACT_CHARS = 500  # a heading or stray line must not be mistaken for the abstract

# Each paragraph is found by a distinctive prefix.  POLARIZATION is split at the sentence
# boundary between differentiation (GEO "growth") and stimulation (GEO "treatment").
ANCHORS = {
    "PBMC_MONOCYTE": "Peripheral blood was diluted with PBS",
    "POLARIZATION": "Freshly isolated monocytes were resuspended",
    "RNA_ISOLATION": "Following stimulation, plates containing cells were put on ice",
    "LIBRARY_PREP": "RNA quality and concentration were assessed",
    "DATA_PROCESSING": "Paired-end RNA-seq reads were aligned",
}
GROWTH_TREATMENT_SPLIT = "Cells were then washed three times with PBS and re-supplemented with macrophage media containing mCSF and TLR or STING agonists"


def paragraphs(docx):
    xml = zipfile.ZipFile(docx).read("word/document.xml").decode("utf8")
    xml = re.sub(r"</w:(p|tr)>", "\n", xml)
    xml = re.sub(r"</w:tc>", " | ", xml)
    text = html.unescape(re.sub(r"<[^>]+>", "", xml))
    return [line.strip() for line in text.split("\n")]


def extract_abstract(docx=MAIN_TEXT):
    """The single paragraph following the 'Abstract:' heading, verbatim."""
    paras = paragraphs(docx)
    heads = [i for i, p in enumerate(paras) if p == ABSTRACT_HEADING]
    if len(heads) != 1:
        raise SystemExit(f"expected 1 {ABSTRACT_HEADING!r} heading, found {len(heads)}")
    for para in paras[heads[0] + 1:]:
        if para:
            if len(para) < MIN_ABSTRACT_CHARS:
                raise SystemExit(
                    f"paragraph after {ABSTRACT_HEADING!r} is only {len(para)} chars -- "
                    "the abstract has probably moved or been split")
            return para
    raise SystemExit(f"nothing follows the {ABSTRACT_HEADING!r} heading")


def extract(docx=STAR_METHODS):
    paras = paragraphs(docx)
    found = {}
    for name, prefix in ANCHORS.items():
        hits = [p for p in paras if p.startswith(prefix)]
        if len(hits) != 1:
            raise SystemExit(f"{name}: expected 1 paragraph starting {prefix!r}, found {len(hits)}")
        found[name] = hits[0]

    polarization = found.pop("POLARIZATION")
    idx = polarization.find(GROWTH_TREATMENT_SPLIT)
    if idx < 0:
        raise SystemExit("polarization paragraph no longer contains the growth/treatment split point")
    found["DIFFERENTIATION"] = polarization[:idx].strip()
    found["STIMULATION"] = polarization[idx:].strip()
    found["ABSTRACT"] = extract_abstract()
    return found


if __name__ == "__main__":
    blocks = extract()
    out = Path(__file__).parent / "protocols_verbatim.py"
    with out.open("w") as fh:
        fh.write(
            '"""Protocol paragraphs copied verbatim from the STAR Methods .docx.\n\n'
            "GENERATED by _extract_protocols.py -- do not edit by hand.  Source:\n"
            f"{STAR_METHODS.name}\n"
            f"{MAIN_TEXT.name} (ABSTRACT)\n"
            '"""\n\n'
        )
        for name in ("ABSTRACT", "PBMC_MONOCYTE", "DIFFERENTIATION", "STIMULATION", "RNA_ISOLATION", "LIBRARY_PREP", "DATA_PROCESSING"):
            fh.write(f"{name} = (\n")
            for chunk in re.findall(r".{1,92}(?:\s|$)", blocks[name]):
                fh.write(f"    {chunk!r}\n")
            fh.write(")\n\n")
    print(f"wrote {out}")
    for name, text in blocks.items():
        print(f"  {name}: {len(text)} chars")
