"""Protocol paragraphs copied verbatim from the STAR Methods .docx.

GENERATED by _extract_protocols.py -- do not edit by hand.  Source:
04_STARMethods_KeyResourcesTable_20260724.docx
Macrophage_text_20260730_v9.docx (ABSTRACT)
"""

ABSTRACT = (
    'Macrophages are central regulators of innate immunity, yet the post-translational mechanisms '
    'that enable rapid inflammatory responses remain poorly understood. Here, we applied an '
    'integrated multi-omic strategy combining transcriptomics, proteomics, cysteine reactivity '
    'profiling, phosphoproteomics, and metabolomics to profile primary human macrophages '
    'following Toll-like receptor (TLR) and STING activation. This approach revealed extensive '
    'post-translational remodeling during macrophage activation, highlighting dynamic regulation '
    'of GTPase signaling, vesicle trafficking, and the endolysosomal system. Among the regulated '
    'proteins, two subunits of the RNA-trafficking FERRY complex emerged as prominent targets of '
    'inflammation-induced post-translational regulation. Biochemical and imaging analyses '
    'demonstrated that the FERRY complex is constitutively assembled in primary human macrophages '
    'and identified previously unrecognized immune-specific protein interactors. Together, this '
    'work provides a comprehensive resource of post-translational regulation during macrophage '
    'activation and nominates the FERRY complex as a potential regulator of innate immune '
    'function.'
)

PBMC_MONOCYTE = (
    'Peripheral blood was diluted with PBS, and 25 mL of the diluted cells were layered over 12.5 '
    'mL of Lymphoprep (STEMCELL Technologies) using 50 mL Falcon tubes. Tubes were centrifuged at '
    'room temperature (900 x g, 25 °C, 20 min) with the acceleration set to 50% and brake '
    'disabled. Following the spin, the plasma and cell layers were transferred to new 50 mL '
    'Falcon tubes, diluted with PBS, and pelleted (520 x g, 25 °C, 8 min). The pellet was washed '
    'once in PBS, resuspended in 5 mL of 1X RBC lysis buffer (Santa Cruz Biotechnologies), and '
    'incubated for 5 min at room temperature. Cells were then diluted with PBS, pelleted (520 x '
    'g, 25 °C, 8 min), and washed with PBS. PBMCs were resuspended at 50 × 10⁶ cells /mL, and '
    'monocytes were isolated by negative selection using the EasySep Monocyte Enrichment Kit '
    'without CD16 Depletion (STEMCELL Technologies) according to manufacturer’s instructions.'
)

DIFFERENTIATION = (
    'Freshly isolated monocytes were resuspended at 1 × 10⁶ cells/mL in macrophage media, '
    'consisting of RPMI-1640 supplemented with 10% FBS (Omega Scientific), 2 mM GlutaMAX (Gibco), '
    '10 U/mL Penicillin-Streptomycin (Gibco), 1 mM Sodium Pyruvate (Gibco), 2 mM HEPES pH 7.0 '
    '(Boston Bioproducts), and 50 ng/mL mCSF (STEMCELL Technologies). Cells were seeded at 15 × '
    '10⁶ cells per 15 cm² culture plate, 5 × 10⁶ cells per 10 cm² culture plate, or 0.83 × 10⁶ '
    'cells per well of a 6-well plate and cultured at 37 °C in a humidified 5% CO2 incubator for '
    'three days. Cells were washed three times with PBS and re-supplemented with macrophage media '
    'containing mCSF for another three days.'
)

STIMULATION = (
    'Cells were then washed three times with PBS and re-supplemented with macrophage media '
    'containing mCSF and TLR or STING agonists (see table below) for 24 h. Cells were then placed '
    'on ice, washed 3x with ice-cold PBS, and harvested into ice-cold PBS by scraping. Cells were '
    'then pelleted (520 x g, 4 °C, 8 min), flash frozen, and kept at -80 °C until further '
    'analysis.'
)

RNA_ISOLATION = (
    'Following stimulation, plates containing cells were put on ice, washed three times with '
    'ice-cold PBS, and the cells were harvested by scraping into ice-cold PBS and transferring to '
    'new Falcon tubes. Cells were then pelleted (520 x g, 4 °C, 5 min), transferred to new low '
    'binding Eppendorf tubes, resuspended in TRIzol reagent (Invitrogen, 15-596-026), snap-frozen '
    'in liquid nitrogen, and stored at -80 °C. RNA was extracted using the Direct-zol RNA '
    'Miniprep kit (Zymo Research, R2052) with on-column DNase I digestion according to '
    'manufacturer’s instructions. Purified RNA was flash frozen and stored at -80 °C until '
    'further analysis.'
)

LIBRARY_PREP = (
    'RNA quality and concentration were assessed using an Agilent Bioanalyzer, and samples with a '
    'RIN > 8 were used for the library prep. 100 ng of total RNA was used to generate RNA-seq '
    'libraries with the Illumina stranded mRNA kit (20040534) according to the manufacturer’s '
    'protocol. Libraries were prepared with unique dual indexes and pooled at equal molar ratios. '
    'The pool was denatured and sequenced on an Illumina NovaSeq 6000 sequencer using V1.5 '
    'reagents, S2 flowcell, and NovaSeq Control Software V1.7.0 to generate 2x100bp paired reads, '
    'according to the manufacturer’s protocol.'
)

DATA_PROCESSING = (
    'Paired-end RNA-seq reads were aligned to the GRCh38 reference genome using STAR (v2.7.7a) in '
    'two-pass mode. The STAR genome index was generated using GENCODE release 44 (Ensembl 110) '
    'gene annotations. Gene-level counts were generated with featureCounts (v1.4.6-p5) in '
    'paired-end mode using the corresponding GENCODE release 44 annotations.'
)

